### ISSUE TITLE
Handle WebSocket connection error

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shinyloadtest#30]
After creating the websocket with `websocket::WebSocket$new()`, be sure to handle the `onError` event.

**Comment by alandipert** [comment]
I noticed while trying to write a test for our server websocket `onError` handling that httpuv partially responds to `Upgrade: websocket` requests even if a WS callback is not defined.

I used httpuv to serve the static assets associated with the `01_hello` example that I created via "Save Complete Webpage" in Firefox. 

Then, I pointed `record_session` at httpuv hoping to see the new `onError` handler print `Server WebSocket error: ...`

Instead of 404-ing or 500-ing, httpuv responded with a 101 to `/websocket` and I saw an error in the R console:

```
> s <- httpuv::startServer("0.0.0.0", 5000, list(staticPaths = list("/" = httpuv::staticPath("tests/01_hello_static/", indexhtml = TRUE))))
> record_session("http://localhost:5000/", host = "0.0.0.0", port = 4349, open_browser = FALSE)
Listening on 0.0.0.0:4349
Client connected
Error in try(private$app$onWSOpen(ws)) : attempt to apply non-function
Server disconnected
Client disconnected
Stopping server
```

**Comment by alandipert** [comment]
Nevermind: I derped. httpuv is 404-ing, it's the httpuv action in shinyloadtest itself that is producing a 101 when it shouldn't (I think)
