### ISSUE TITLE
Recording fails on Windows

### ISSUE THREAD

**Issue by alandipert** [rstudio/shinyloadtest#41]
I started the proxy server with `shinyloadtest::record_session("https://beta.rstudioconnect.com/content/3843/")`

On Windows 10 in VMware, recording will occasionally fail:

<img width="1163" alt="screen shot 2018-09-04 at 11 55 55 am" src="https://user-images.githubusercontent.com/26024/45051677-9be68380-b039-11e8-85cf-289131132772.png">

Based on the stack trace, it looks like SockJS is falling back to the `xhr-streaming` transport which then fails with a 405.

This seems to happen when a recording is attempted for the first time in an R session. If I `Ctrl-c` in RStudio, run `record_session` again, and reload the browser, the application loads normally.

Disabling all other protocols except `websocket` via `Ctrl-Shift-Option A` doesn't seem to help. The application still fails to load, but no 405 error is observed in the console.

**Comment by jcheng5** [comment]
OK, it's a timing issue, but a surprisingly sophisticated one. Here's a trace in Wireshark:

![image](https://user-images.githubusercontent.com/129551/45063895-77a09c00-b065-11e8-8f55-45e487fe2c3e.png)


The second column from the left is the number of seconds elapsed since the start of the capture. About 640 milliseconds after the WebSocket connection is opened, the SockJS client slams the door. Seems like a pretty short timeout, right? This is because the timeout is actually dynamically calculated.

1. Before SockJS attempts to actually connect via WebSocket or any other protocol, it first makes a `GET` request to a `/__sockjs__/.../info` endpoint. It keeps track of how long it takes for the response to be received; let this time be `rtt` (round trip time). In the trace above, that's 98ms.
2. Use [this algorithm](https://github.com/sockjs/sockjs-client/blob/0c70698bddcfab826c7b241ed709f69b5b0d41f7/lib/utils.js#L82-L90) to convert `rtt` to `rto` (retransmission time out, or possibly roundtrip time out). This is the maximum amount of time the SockJS client is willing to wait for each roundtrip message.
3. Each SockJS transport method has an attribute `roundtrips` that says approximately how many round trips are needed before an `open` message is received. For WebSocket, [`roundtrips = 2`](https://github.com/sockjs/sockjs-client/blob/0c70698bddcfab826c7b241ed709f69b5b0d41f7/lib/trans-websocket.js#L60).
4. Therefore, after the WebSocket connection is established, the client will wait `(98 + 200) * 2` or ~600ms before it gives up.

So far I have these workarounds we can choose from:

1. Send the `"o"` message faster, i.e. don't wait to proxy the `"o"` coming from the server. We'd need to make sure we only send it when it's a SockJS connection, not regular WebSocket.
2. Slow down the `/info` request artificially with a `Sys.sleep`; I'm guessing something between 0.5 and 1.5 would be appropriate? Q: Would this affect the timing of playback? i.e. does shinycannon do a wait between `REQ_SINF` and `WS_OPEN`?
